name: Build and Deploy Flutter Web to Netlify

on:
  push:
    branches: [master, main]
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Check Flutter version
        run: flutter --version

      - name: Install dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: frontend
        run: flutter build web --release --dart-define=API_BASE_URL=${{ secrets.API_BASE_URL }}

      - name: Install Netlify CLI
        run: |
          npm install -g netlify-cli

      - name: Reset Netlify config permissions
        run: |
          rm -rf ~/.config/netlify
          mkdir -p ~/.config/netlify

      - name: Netlify Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify deploy --dir=frontend/build/web --prod --site=${{ secrets.NETLIFY_SITE_ID }} --auth=${{ secrets.NETLIFY_AUTH_TOKEN }}
